# Generated by Django 4.2.5 on 2024-05-13 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('discount', models.IntegerField()),
                ('in_stock', models.IntegerField()),
                ('fast_sales', models.BooleanField(default=False)),
                ('views', models.PositiveIntegerField(default=0)),
                ('featured', models.BooleanField(default=False)),
                ('Fast', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('Cream', 'Cream'), ('Lotion', 'Lotion'), ('Haircream', 'Haircream'), ('pancake', 'pancake'), ('Powder', 'Powder'), ('Eyebrown', 'Eyebrown'), ('Eyelashes', 'Eyelashes')], max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
